apiVersion: v1
kind: Service
metadata: 
  name: testonlinebook-load
spec:
  type: LoadBalancer
  ports:
    - name: tomcat
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: testonlinebooksto
