apiVersion: v1
kind: service
metadata: 
  lables:
    run: testonlinebook
    namespace: default
spec:
  type: LoadBalancer
  ports:
  - name: tomcat
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: testonlinebook
